### PR TITLE
fix for strange use of use_spatial boolean

### PR DESCRIPTION
**Pull request by zsinnema**
see #43

removed == 'full' check on boolean use_spatial

### CODE REVIEW

**Review by phildong — COMMENTED** [review]
what's the purpose of this? I don't think this is equivalent since `use_spatial` can take values other than `full` and the algorithm should do different things.
Now I don't think this parameter actually ever works properly (I have never set `use_spatial` to something other than `None`), so in the future we can deprecate this completely. But I don't think we are ready for that.

**Comment by zsinnema** [comment]
@phil the purpose is that at this moment use_spatial everywhere is used (and set) as a boolean value except the changed line. Thus to make it consistent across the project.

**Comment by phildong** [comment]
well it's not supposed to be boolean at least when I wrote it

**Comment by zsinnema** [comment]
you can see it here:
https://github.com/MetaCell/minian/blob/ac3331e279517f128976aedcdde6d0477018e7fb/minian/cnmf.py#L387
and here:
https://github.com/MetaCell/minian/blob/ac3331e279517f128976aedcdde6d0477018e7fb/minian/cnmf.py#L443
and here:
https://github.com/MetaCell/minian/blob/ac3331e279517f128976aedcdde6d0477018e7fb/minian/cnmf.py#L544

**Comment by phildong** [comment]
yes I'm aware of those and they look confusing, but they don't necessarily imply `use_spatial` is boolean since you can put a lot of random stuff after `if` in python.
I don't think it's worth spending more time on this given how this parameter is never used.

**Comment by phildong** [comment]
If you can't bear the confusion I guess you can change the default from `False` to `None`.
Again I don't think that's something we should be focusing now.

**Comment by zsinnema** [comment]
the only change I did is change this:
```
if use_spatial == 'full':
```
into 
```
if use_spatial:
```
the initial value was already set to False

**Comment by wmau** [comment]
@zsinnema What @phildong is saying is that the intended data type for `use_spatial` is not a boolean so your change would produce unexpected outputs. This particular conditional statement is a work in progress so it's better to leave it alone for now.

**Pull request closed without merging**
